apiVersion: apps/v1
kind: Deployment
metadata:
  name: exposeuserservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exposeuserservice
  template:
    metadata:
      labels:
        app: exposeuserservice
    spec:
      containers:
      - name: exposeuserservice
        image: johannesdigdir/exposeuser_service:ef41f6206e3a8adffcd1eb7e605c6a96d2e1f291
        ports:
        - containerPort: 5000