apiVersion: apps/v1
kind: Deployment
metadata:
  name: exposeuserservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exposeuserservice
  template:
    metadata:
      labels:
        app: exposeuserservice
    spec:
      containers:
      - name: exposeuserservice
        image: johannesdigdir/exposeuser_service:0db3ff3e4948a1b9231d6ce6ba187482eb852f45
        ports:
        - containerPort: 5000