apiVersion: apps/v1
kind: Deployment
metadata:
  name: exposeuserservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exposeuserservice
  template:
    metadata:
      labels:
        app: exposeuserservice
    spec:
      containers:
      - name: exposeuserservice
        image: johannesdigdir/exposeuser_service:53faab4e41d0390e0bea86e5b9fc321a27c17f39
        ports:
        - containerPort: 5000